R/population-workflow.R
tests/dev/test-raltegravir-nonparallel-population.R

small bug fix - pop SA wasn't looping over all simulation sets

Add loop over simulation sets for pop sa

---

R/population-workflow.R
tests/dev/test-raltegravir-nonparallel-population.R

another small bug: pop SA results index file was being overwritten for each simulation set

added prefix to pop SA index results file name

---

R/utilities-writing-report.R
man/addFigureChunk.Rd

percentage sign in documentation was causing errors

fix installation warnings re addFigureChunk

---

R/pk-parameter-info.R
R/utilities-sensitivity-analysis.R
R/utilities-tracelib.R
tests/dev/test-population-sensitivity-invalid-PK.R
tests/dev/test-population-sensitivity-plot3.R
tests/testthat/test-output.R

Fixes #214 
Fixes #218 
Fixes #257 
Use displayName for output and pkparameter in pop sensitivity plot output captions

Use displaynames in pop sens plot

---

R/utilities-calculate-pk-parameters.R
R/utilities-demography.R

@msevestre if build passes and if @TWendl is okay with the update, 
I think we can merge

318 demography plot

---

DESCRIPTION
appveyor.yml

Updating version of ospsuite-r to be 9.1.4 (also with min requireements)

Fixes #278 display parameters

---

NEWS.md

Open for suggestions in the writing of the news.
https://style.tidyverse.org/news.html suggest the following sections:

Fixes #404 document changes between releases

---

NEWS.md
R/workflow.R
man/Workflow.Rd
vignettes/introduction-re-instances.Rmd

Let me know if I forgot anything in what is new for v1.2

Documentation update

---

R/simulation-set.R
man/SimulationSet.Rd
vignettes/goodness-of-fit.Rmd
vignettes/introduction-re-instances.Rmd

Fixes #419 simulation set input is the names of selected applications

---

R/qualification-outputs.R
R/qualification-pk-ratio.R
R/utilities-task.R
man/getQualificationPKRatioMeasure.Rd

Below are some bugs I fixed when I tried to run the qualification test of #525

525 testing qualification project

---

R/utilities-qualification.R
inst/extdata/qualification-workflow-template.R
man/startQualificationRunner.Rd

Also updates the qualification workflow template based on -n requirements

Fixes #609 use system instead of shell

---

R/qualification-ddi.R

- Increase size of tick font size
- Fixes #613
- Re: #614 Change horizontal/diagonal, 2-fold and Guest lines to black solid.

Fix ddi formatting

---

R/qualification-pk-ratio.R

Fix ratio calculation due to display unit of obs and sim data in table

---

R/qualification-comparison-time-profile.R
R/qualification-gof.R

Would it be possible to get a test with multiple observed data ?
I want to make sure it is `ObservedData` and not `ObservedDataSets`

Fixes #60 multiple observed data in comparison time profile and GOF plots

---

inst/extdata/re-theme.json

yticklabels are right aligned to make prettier sensitivity plots

Fixes #799 axes titles are centered

---

R/qualification-ddi.R

@Yuri05 I did not get this issue when testing with my current R version, could you check that this fix actually solved the issue

Fixes #837 enforce removal of Caption in legend title

---

R/configuration-plan.R
tests/data/qualification/Inputs/input.md
tests/data/qualification/report-configuration-plan.json
tests/testthat/test-qualification.R

need to have the bugfix https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/issues/899 in the release
I will replace the release [2.0.189](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/releases/tag/v2.0.189) with the new version (luckily it is still a pre-release :)

Version 2.0.191

---

R/utilities-configuration-plan.R
inst/extdata/re-theme.json
man/ConfigurationShapes.Rd

Note that the new method leads to smaller symbols that are scaled bigger in the RE theme

Fixes #949 add new symbols to dictionary

---

.github/workflows/Check_utf8.yml
.github/workflows/Dockerfile
.github/workflows/install_packages_cran.sh
DESCRIPTION
appveyor.yml

Fixes #1012 Exclude PRs when installing packages from the latest AppVeyour build

Fixes #1011 Increment version 2.1=>2.2

---

R/qualification-ddi.R

From local tests, the html is correctly displayed in md and translated by pandoc in the docx. 
@Yuri05 Let me know if this works on your side

Fixes #1069 display delta appropriately

---

appveyor.yml

Also deactivated Code Coverage

Fixes #1107 Package build: are the vignettes built twice?

---

inst/extdata/re-theme.json

Reverts Open-Systems-Pharmacology/OSPSuite.ReportingEngine#1125
The change of angle reference for right axis is now handled by tlf

Revert "Fix default angle for y2label"

---

R/calculate-pk-parameters-task.R
R/messages.R
R/simulation-settings.R
man/SimulationSettings.Rd

Note that the progress bar is now displayed by default

Fixes #1176 display progress bar for PK parameters calculation

---

R/utilities-plots.R

Here is the resulting plot in my test
<details><summary>Figure</summary>
<details>

Fixes #1248 DDI plots are quadratic
