Open-Systems-Pharmacology/OSPSuite.ReportingEngine

DESCRIPTION
tests/testthat/test-output.R
tests/testthat/test-tasks-in-workflow.R

Depends auto loads dependent packages while Import does not
For more information: https://kbroman.org/pkg_primer/pages/depends.html

Fixes #76 autoload tlf and ospsuite

---

R/population-workflow.R
man/PopulationWorkflow.Rd

Before the method was available with new() for mean model workflow
and for both workflows using setSimulationDescriptor()

Fixes #423 pop workflow can be initialized with simulationSetDescriptor

---

tests/testthat/test-mean-pk-parameters.R

The code behaviour is correct, however the tests fail due to the "µ-conversion when reading units from file.

disabled 2 pk-parameters tests on Linux.

---

R/qualification-comparison-time-profile.R
R/qualification-gof.R
R/qualification-pk-ratio.R
R/qualification-time-profile.R
R/utilities-calculate-pk-parameters.R
R/utilities-demography.R
R/utilities-goodness-of-fit.R
R/utilities-mass-balance.R
R/utilities-sensitivity-analysis.R

The RE function loadSimulationWithUpdated path does not add to cache and is used for absorption. So there should not be any side effect when including loadFromCache

Fixes #583 use loadFromCache when possible

---

R/qualification-ddi.R
R/utilities-plots.R

- restore DDI axis labels that were no longer appearing
- restore DDI legend position to `outsideRight`
[currentReport.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/files/7783755/currentReport.zip)

fix DDI axis labels and legend positions

---

R/error-checks.R
R/messages.R
R/utilities-qualification.R
inst/extdata/qualification-workflow-template.R

The error message from `jsonlite` was not helpful because the function accepts both a path of json file and its content.
I have included a `validateIsFileExtension` from reporting engine as the method is not yet in `{ospsuite.utils}`

Fixes #665 typo in template

---

R/qualification-gof.R

The crash actually came from the auto scaling of the axes.
Since the data included Inf, ggplot was trying to scale to Inf and crashed (the Inf data point only leads to warnings from ggplot).
For tlf, this means there needs to be 2 layers in handling Inf and NAs: one regarding the data points to plot and one preventing scaling by Inf values

Fixes #672 prevent crash of gof plot when Inf values are introduced

---

R/qualification-workflow.R

Currently, only PKRatio and DDIRatio plots require this task

Fixes #722 PK Parameters are not run if not required

---

R/utilities-simulation.R

In case of simple warning, the simulations that worked are currently re-run and output. Let me know if this needs to be changed

FIxes #728 simulation errors are not catched

---

R/utilities-calculate-pk-parameters.R

`{ggplot2}` crashes when logticks can't be added on log plots (`Error in unit(yticks$start, "cm")`)
The issue was encountered a while ago for boxplots and was fixed by calculating sensible ticks and limits then. Since range plots use the same data, the boxplot ticks and limits can be re-used.

Fixes #909 use limits and ticks from boxplots for range plots

---

inst/extdata/re-theme.json

For some reason, the properties defined in color and linetype of ribbons are actually used to create the legend key even if they are not used by the ribbon itself. Using a blank linetype remove the line from the legend key.

Fixes #811 remove blue line from legend shaded area

---

R/utilities-writing-report.R

Actually, this was not a pandoc issue but a missing `overwrite` parameter in `copyReport()`

Fixes #1055 update word reports

---

R/utilities-writing-report.R
tests/data/utilities-report/testReportNumFigs.md
tests/data/utilities-report/testReportNumSecs.md
tests/data/utilities-report/testReportNumToc.md

The auto-numbering algorithm for Figures assumes that the caption is below the figure. In the qualification example, it was above. The fix renders a more robust way of including the bookmarks before the figure without needing a placeholder for the md figure inclusion line

Fixes #1071 auto-numbering does not mess up static images

---

R/qualification-time-profile.R

@Yuri05 
I was not expecting the following behavior from the function `isEmpty` (from the package `{ospsuite.utils}`):
A named list with only `NULL` elements is not considered empty while a data.frame with only `NULL` columns is empty.
```r
> isEmpty(list(a=NULL))
[1] FALSE
> length(list(a=NULL))
[1] 1
> isEmpty(data.frame(a=NULL))
[1] TRUE
> length(data.frame(a=NULL))
[1] 0
```
Let me know if this requires also an update on the `{ospsuite.utils}` side ?

Fixes #1082 no observed data does not crash qualification time profile

---

R/messages.R
R/utilities-ratio-comparison.R

With this PR the new messages are
$\text{\color{green}{i Info} \color{black}{Simulation Set '}\color{blue}{simulation set name}\color{black}{' was identified with population} \color{blue}{same} \color{black}{from reference '}\color{blue}{Reference simulation set name}'.}$
$\text{\color{black}{Ratio comparison of} \color{blue}{PK Parameter} \color{black}{of} \color{blue}{Output path} \color{black}{uses} \color{blue}{Individual PK Ratios} \color{black}{for analyzing statistics.}}$
$\text{\color{green}{i Info} \color{black}{Simulation Set '}\color{blue}{simulation set name}\color{black}{' was identified with population} \color{blue}{different} \color{black}{from reference '}\color{blue}{Reference simulation set name}'.}$
$\text{\color{black}{Ratio comparison of} \color{blue}{PK Parameter} …

Fixes #1085 Update ratio message to indicate PK parameter

---

README.md

No functional changes, just an update of installation instructions.
It turned out that for correct conversion of reports with SVG images from .MD to .docx via Pandoc one extra command line utility is required: **rsvg-convert**.
Under Linux it's part of librsvg package, under Windows it can be installed as a standalone command line tool.

Fixes #1016

---

R/mean-model-workflow.R
R/population-workflow.R
R/qualification-workflow.R
R/utilities-logging.R
R/utilities-qualification.R
man/resetLogs.Rd
man/setLogFolder.Rd
tests/testthat/test-configuration-plan.R
tests/testthat/test-ddi-report.R
tests/testthat/test-logging.R
tests/testthat/test-workflow-structure.R

I was not able to reproduce issue #1168.
I identified 2 potential reasons for the 5 failed tests:
1- new messages are logged in the old workflow folders (this PR aims at preventing that)
2- unexpected warning messages are thrown and logged in the local tests (such as functions deprecated, etc.)
If possible, couId you send the log-error.txt so that I can identify the message.
Best case, I can include the message into the list of message that `logCatch` needs to mute and log in the debug files: https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/blob/37541521906fdd6b22347837179f6b58291faef5/R/utilities-logging.R#L169-L180

Fixes #1168 prevent logging of new messages in old workflow folders

---

R/configuration-plan.R
R/error-checks.R
R/gof-plot-task.R
R/qualification-gof.R
R/qualification-pk-ratio.R
R/qualification-time-profile.R
R/reportingengine-env.R
R/task-results.R
R/task.R
R/utilities-demography.R
R/utilities-goodness-of-fit.R
R/utilities-mpi-error-handling.R
R/utilities-plots.R
R/utilities-qualification.R
R/utilities-ratio-comparison.R
R/utilities-task.R
R/utils.R
man/addLLOQLegend.Rd
man/getLegendAesOverride.Rd

34 TODOs were identified and removed

Fixes #67 Remove TODOs and create actual issues

---

R/utilities-logging.R

Initial issue message in #1056 and warning in #850 
``` r
p <- ggplot(data.frame(x=1,y=0), aes(x=x,y=y)) +
geom_path() + 
scale_y_log10()
ggsave(
plot = p,
filename = "warning.png",
width = 5, height = 5
)
#> Warning in scale_y_log10(): log-10 transformation introduced infinite values.
#> `geom_path()`: Each group consists of only one observation.
#> ℹ Do you need to adjust the group aesthetic?
```
<sup>Created on 2024-03-06 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
__Fix using `logCatch()`__
``` r
library(ospsuite.reportingengine)
#> Loading required package: ospsuite
#> 
#> Loading required package: rClr
#> 
#> Loading the dynamic library for Microsoft .NET runtime...
#> Loaded Common Language Runtime version 4.0.30319.42000
#> 
#> 
#> Loading required package: tlf …
```

Fixes #850 Fixes #1056 handling of messages and warnings

---

vignettes/add-title-page.Rmd
vignettes/demography.Rmd
vignettes/excel-template.Rmd
vignettes/goodness-of-fit.Rmd
vignettes/mass-balance.Rmd
vignettes/ospsuite-reportingengine.Rmd
vignettes/pk-parameters.Rmd
vignettes/plot-settings.Rmd
vignettes/pop-pk-parameters.Rmd
vignettes/qualification-workflow.Rmd
vignettes/sensitivity-analysis.Rmd
vignettes/word-report.Rmd

> [!NOTE]
> Since the templates are downloaded within the documentation site, we can use relative links and each site can use `develop` or `main`/`release` as appropriate

Fixes #1212 download the templates within the documentation site

---

R/messages.R
R/qualification-ddi.R

@Yuri05 
Here is an example of message when skipping the plot
```r
! Warning	DDI plot 'Pgp DDI' for subunit 'Victim: Digoxin' of predictedVsObserved 'AUC_tEnd' ratios was skipped because no data was available
```

Fixes #1285 skip DDI plots when no non missing data are available

---

R/qualification-comparison-time-profile.R

The filter is already applied before creating ymin and ymax. In this case, since the filter was removing the first data point, it shifted all the error bars

Fixes #1343 remove redundant data filter

---

R/utilities-plots.R

The issue `$ operator is invalid for atomic vectors` comes from `cowplot` update. (see [#101](https://github.com/Open-Systems-Pharmacology/Workflows/issues/101) for more details)
The latest version 1.2.0 has a simplified `get_legend()` function that does exactly what we needed but in exchange, the previous workflow from version 1.1.3 leads to an empty grob that was crashing the workflows

Handle cowplot update
